### ISSUE TITLE
New rocksdb-haskell-kadena dependency does not build on macOS

### ISSUE THREAD

**Issue by jwiegley** [kadena-io/chainweb-node#1537]
Building the latest chainweb-node on Mac does not seem to work. This is due to a compilation failure in rocksdb by way of the new rocksdb-haskell-kadena dependency introduced in 6e5d32bc11dc21e8d3ad6e70d188d902a26c560d. The exact error looks like:
```
rocksdb-6.29.3/util/crc32c.cc:757:13: error:
     error: always_inline function '_mm_crc32_u64' requires target feature 'sse4.2', but would be inlined into function 'crc32c_3way' that is compiled without support for 'sse4.2'
                CRCtriplet(crc, next, -128);
                ^
    |
757 |             CRCtriplet(crc, next, -128);
    |             ^
```
Since we've decided to support Mac as a production deployment platform, we’ll need a way for CI to catch discrepancies like this. Or is it just happening because of the Nix environment that we’ve pinned in default.nix? I’m still gathering information.

A possibly relevant note, from https://github.com/chakra-core/ChakraCore/issues/3551:
>Unfortunately if -msse4.2 is enabled then SSE4.2 instructions will be enabled globally throughout the codebase. This means that Clang is free to emit SSE4.2 code wherever it pleases (not just where you have used an intrinsic such as _mm_crc32_u32). This means it will generate code that will not work correctly on processors that only have support for SSE2. I think this is an example of how Clang differs in behaviour to MSVC. I think MSVC will only emit SSE4.2 instructions specifically where you have used SSE4.2 intrinsics.
